name = "STRtree"
uuid = "746ee33f-1797-42c2-866d-db2fce69d14d"
authors = ["Max Freudenberg <maximilian.freudenberg@uni-goettingen.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
